### ISSUE TITLE
Add options to pass in styling without css

### ISSUE THREAD

**Issue by Tranquility** [mercurymedia/elm-smart-select#13]

**Comment by jmpressman** [comment]
@mschindlerMM @t8p @Tranquility @exolab 

In your respective opinions, why, if at all, do we need the ability to pass inline styles to the select component?

If it is to allow select instances to be styled differently throughout the app, wouldn't it be more simple to have the user pass in a unique identifier for each instance that gets added to the picker class names?

I just want to make sure I don't spend a lot of time on this if there isn't really a reason to do it in the first place.

If however we do determine that we need inline styling capabilities, it would be great to have a quick session to go over the different approaches that I have been thinking about.

**Comment by Tranquility** [comment]
For me this is just to not need css anymore. Copying and a css file is not a nice user experience and makes changing things really difficult because the api does not change when we change the HTML of the select. When we add or remove classes the css needs to be updated and this becomes really problematic when we have different versions of the package in the application because they might require a different css.

But it this issue does not have a very high priority for me.

**Comment by hingew** [comment]
I think this is done in #57 and #60.
