### ISSUE TITLE
Feedback: How to show examples in browser?

### ISSUE THREAD

**Issue by andys8** [mercurymedia/elm-smart-select#7]
Hey, 

currently the examples will spit out a javascript file. I can't figure out where html (and the usage of styles) is or should be happening. Therefore I can't see how they can or should be shown in the browser :)

https://github.com/mercurymedia/elm-smart-select/blob/4d2a5b3a4d250b44cb4c66e1104fe7abf49d6432/examples/Makefile#L7

**Comment by jmpressman** [comment]
Hi Andy, thanks for the feedback! I will look into making the examples a little more user friendly to setup this weekend.

In the meantime, if you look in the examples folder, there are two directories in addition to the make file. These directories contain the index.html files that the js output goes into. Additionally, the index.html files include the SmartSelect.css.

You should be able to see the examples by opening the index.html files in your browser. Let me know if you have any other questions/concerns!

**Comment by andys8** [comment]
Thanks for the reply. I'm looking over multiple libraries and it would be nice if the instructions are super easy to give it a quick try.

Thanks for the hint regarding `index.html` files location.

**Comment by hingew** [comment]
Hey, now its possible to run `npm start` to see the examples in the browser.
